api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Bundler Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:1.17.3:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@1.17.3?checksum=bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352&download_url=https://rubygems.org/downloads/bundler-1.17.3.gem"
    sha256 = "d59b0711914a7876a10032d925811b9cfe87a1e9f87c82a861c3d69bb6857e93"
    source = "https://rubygems.org/downloads/bundler-1.17.3.gem"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/bundler/bundler_1.17.3_linux_noarch_bionic_d59b0711.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.19:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.19?checksum=bb32b7d2c661f3f2120ee25112d39470f22295a575623782dcbfa32e18a81af1&download_url=https://rubygems.org/downloads/bundler-2.3.19.gem"
    sha256 = "6563ad354b8d0644a828a9c303aa0f6947b76f268ed6ece4b9acaef66c4ee68d"
    source = "https://rubygems.org/downloads/bundler-2.3.19.gem"
    source_sha256 = "bb32b7d2c661f3f2120ee25112d39470f22295a575623782dcbfa32e18a81af1"
    stacks = ["bionic\n"]
    uri = "TBD - needs to be uploaded to S3"
    version = "2.3.19"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.19:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.19?checksum=bb32b7d2c661f3f2120ee25112d39470f22295a575623782dcbfa32e18a81af1&download_url=https://rubygems.org/downloads/bundler-2.3.19.gem"
    sha256 = "1e8e5cf5bc298153ba5cf0be0a8200e7c9f68543a54ff550c38448712c50f99e"
    source = "https://rubygems.org/downloads/bundler-2.3.19.gem"
    source_sha256 = "bb32b7d2c661f3f2120ee25112d39470f22295a575623782dcbfa32e18a81af1"
    stacks = ["jammy\n"]
    uri = "TBD - needs to be uploaded to S3"
    version = "2.3.19"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.20:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.20?checksum=809277bc7ceb268e97a474b58b02dbefb8ddf59077f4618b70e2504ab81a047c&download_url=https://rubygems.org/downloads/bundler-2.3.20.gem"
    sha256 = "2051881f15b7ea7a64fde5af5d424e89d7eeed3f6d06cbfb0400757cffc1fd5d"
    source = "https://rubygems.org/downloads/bundler-2.3.20.gem"
    source_sha256 = "809277bc7ceb268e97a474b58b02dbefb8ddf59077f4618b70e2504ab81a047c"
    stacks = ["bionic\n"]
    uri = "TBD - needs to be uploaded to S3"
    version = "2.3.20"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.20:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.20?checksum=809277bc7ceb268e97a474b58b02dbefb8ddf59077f4618b70e2504ab81a047c&download_url=https://rubygems.org/downloads/bundler-2.3.20.gem"
    sha256 = "e8240f555ccc1b8e892f32149e1cb6a160df35e87220c3d6b2ee2e79d57d8600"
    source = "https://rubygems.org/downloads/bundler-2.3.20.gem"
    source_sha256 = "809277bc7ceb268e97a474b58b02dbefb8ddf59077f4618b70e2504ab81a047c"
    stacks = ["jammy\n"]
    uri = "TBD - needs to be uploaded to S3"
    version = "2.3.20"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.21:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.21?checksum=faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de&download_url=https://rubygems.org/downloads/bundler-2.3.21.gem"
    sha256 = "e4d695642a4957dcdaa6ceafc2ccc342ee4d52e5ecef26ebb4deec702ee4763e"
    source = "https://rubygems.org/downloads/bundler-2.3.21.gem"
    source_sha256 = "faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de"
    stacks = ["bionic\n"]
    uri = "TBD - needs to be uploaded to S3"
    version = "2.3.21"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.21:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.21?checksum=faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de&download_url=https://rubygems.org/downloads/bundler-2.3.21.gem"
    sha256 = "f0f17a0366625fe20c1149e42da1ec6dee1e5d157605a17963890ad4484af502"
    source = "https://rubygems.org/downloads/bundler-2.3.21.gem"
    source_sha256 = "faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de"
    stacks = ["jammy\n"]
    uri = "TBD - needs to be uploaded to S3"
    version = "2.3.21"

  [[metadata.dependency-constraints]]
    constraint = "1.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 3

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
