api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Bundler Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:1.17.3:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@1.17.3?checksum=bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352&download_url=https://rubygems.org/downloads/bundler-1.17.3.gem"
    sha256 = "dc89db5382e681b4c03b48dae8be4238b077a45e52488233ab01c0e93b913dc7"
    source = "https://rubygems.org/downloads/bundler-1.17.3.gem"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "file:///Users/caseyj/git/paketo-buildpacks/bundler/dependency/bundler-1.17.3.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "b335dd4c52c0cdf8800ef8db32ff9723593dc989e4994d4f34090deddbbc50d8"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "d1b4b141fb281dcd7debc02c7509d06c6a8693156d3016d8a674fbe644da1703"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "22d7930472f1a029c629e0ea1bad8ba595488c56f2f9cafd2fa3e7902efa0e30"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "200b92815a51caf8364cd077bc4030575f85900dc686d72bf524807115e3336e"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "62a716ff3fdb9db1580583796c2c6191cf6bfa3b40aa1321082e9147e0b3eae6"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "d39c419fe49fe8f48daad2bb94cb1c8f60b44f03054a1bc96c25d9b50a5d3b34"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "53f85ef30106784ad0912580bd39141e7c68c4b85a0a2911882704d3c4366876"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "4d61dcab177109301673498af84530399fdf97c4fe17a511ae858811db82abd1"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "932043fb565988cac29e94992e56e09a506efa367cb919a287abe4bc0a99ba43"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.14:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.14?checksum=2fae2925c22ae122b245416484373a139d57a3e123fe9baed98d407384ea803c&download_url=https://rubygems.org/downloads/bundler-2.3.14.gem"
    sha256 = "de0087f28b79870211e45e52776680e04c1d4c9c9f34fee0f48650e65f8f5c33"
    source = "https://rubygems.org/downloads/bundler-2.3.14.gem"
    source_sha256 = "2fae2925c22ae122b245416484373a139d57a3e123fe9baed98d407384ea803c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/bundler/bundler_2.3.14_linux_noarch_bionic_de0087f2.tgz"
    version = "2.3.14"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "6c368ee80241a2efa1d618a1b5c6b95fa17638000203535eb7531568520d3a23"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "eef5bf00cc6c708ee52c12f19f8b2c46826eaf7b3e50cbd69be08d3ab939a7f4"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "f4518d1e1d03c83656eb400bd5b591b5ce60ae6c1cdc6c1c070e36a7952ffd6d"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "c67641c825f3bdd774aedf6cadd83becafe30a8833ac4201d25f1d491cff826c"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "73980e3517bdcbab6b4f4e3f48d17312e14508ad11af2bde5a1b04c6af0ee397"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "7e36b76797cbd27488e48a6aea07cafd90a3c8d8854ec404b22295b351cadcc5"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "5e89a28253a708116a2b71b6a0176d8373f5d7a8a4b41958e131944afbe439a6"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "b47a2e51cfa3fc51864f750ba2786b9034a2e963f6dcc2d796715aa8ecc6b137"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "c4ce2519f53ff236ecbc816b237f360d6387e44940d68e9c0cd6730be36ea2bd"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependency-constraints]]
    constraint = "1.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 3

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
