api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Bundler Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:1.17.3:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@1.17.3?checksum=bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352&download_url=https://rubygems.org/downloads/bundler-1.17.3.gem"
    sha256 = "d59b0711914a7876a10032d925811b9cfe87a1e9f87c82a861c3d69bb6857e93"
    source = "https://rubygems.org/downloads/bundler-1.17.3.gem"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/bundler/bundler_1.17.3_linux_noarch_bionic_d59b0711.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.20:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.20?checksum=809277bc7ceb268e97a474b58b02dbefb8ddf59077f4618b70e2504ab81a047c&download_url=https://rubygems.org/downloads/bundler-2.3.20.gem"
    sha256 = "bfabce4173b5dc2dbf399d1cd33453790176fb2b3f5da82f25ce77608fd60c81"
    source = "https://rubygems.org/downloads/bundler-2.3.20.gem"
    source_sha256 = "809277bc7ceb268e97a474b58b02dbefb8ddf59077f4618b70e2504ab81a047c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/bundler/bundler_2.3.20_linux_noarch_bionic_bfabce41.tgz"
    version = "2.3.20"

  [[metadata.dependencies]]
    checksum = "sha256:19630288abd04c6775e7095aaca104ce4d8bf569c2364f30a417c9d71acc152f bundler-2.3.21-bionic.tgz"
    cpe = "cpe:2.3:a:bundler:bundler:2.3.21:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.21?checksum=faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de&download_url=https://rubygems.org/downloads/bundler-2.3.21.gem"
    source = "https://rubygems.org/downloads/bundler-2.3.21.gem"
    source-checksum = "sha256:faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "random-uri"
    version = "2.3.21"

  [[metadata.dependencies]]
    checksum = "sha256:090e856dcb0ac5c520c33f811a7465dd3646ea3984157d4031e642e07e90809a bundler-2.3.21-jammy.tgz"
    cpe = "cpe:2.3:a:bundler:bundler:2.3.21:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.21?checksum=faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de&download_url=https://rubygems.org/downloads/bundler-2.3.21.gem"
    source = "https://rubygems.org/downloads/bundler-2.3.21.gem"
    source-checksum = "sha256:faedc7ffc167a3c53b64c463da67b50d5be43804761de5a68dda344c21bfd1de"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "random-uri"
    version = "2.3.21"

  [[metadata.dependencies]]
    checksum = "sha256:89e5389aed7eaa1f093d94b1b8832803f80cd342a6af48b01c3aad1426739f8a bundler-2.3.22-bionic.tgz"
    cpe = "cpe:2.3:a:bundler:bundler:2.3.22:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.22?checksum=bce7d907aa683ac8983d42da1a15170fd692c6504678ada0845ef4a2ecf4209e&download_url=https://rubygems.org/downloads/bundler-2.3.22.gem"
    source = "https://rubygems.org/downloads/bundler-2.3.22.gem"
    source-checksum = "sha256:bce7d907aa683ac8983d42da1a15170fd692c6504678ada0845ef4a2ecf4209e"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "random-uri"
    version = "2.3.22"

  [[metadata.dependencies]]
    checksum = "sha256:b03576d45de9f9b91fb5c2b9b5dd09a2be3c4cb908d007e483054de7b977577d bundler-2.3.22-jammy.tgz"
    cpe = "cpe:2.3:a:bundler:bundler:2.3.22:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.22?checksum=bce7d907aa683ac8983d42da1a15170fd692c6504678ada0845ef4a2ecf4209e&download_url=https://rubygems.org/downloads/bundler-2.3.22.gem"
    source = "https://rubygems.org/downloads/bundler-2.3.22.gem"
    source-checksum = "sha256:bce7d907aa683ac8983d42da1a15170fd692c6504678ada0845ef4a2ecf4209e"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "random-uri"
    version = "2.3.22"

  [[metadata.dependency-constraints]]
    constraint = "1.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 3

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
