api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Bundler Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:1.17.3:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@1.17.3?checksum=bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352&download_url=https://rubygems.org/downloads/bundler-1.17.3.gem"
    sha256 = "dc89db5382e681b4c03b48dae8be4238b077a45e52488233ab01c0e93b913dc7"
    source = "https://rubygems.org/downloads/bundler-1.17.3.gem"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "file:///Users/caseyj/git/paketo-buildpacks/bundler/dependency/bundler-1.17.3.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.14:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.14?checksum=2fae2925c22ae122b245416484373a139d57a3e123fe9baed98d407384ea803c&download_url=https://rubygems.org/downloads/bundler-2.3.14.gem"
    sha256 = "de0087f28b79870211e45e52776680e04c1d4c9c9f34fee0f48650e65f8f5c33"
    source = "https://rubygems.org/downloads/bundler-2.3.14.gem"
    source_sha256 = "2fae2925c22ae122b245416484373a139d57a3e123fe9baed98d407384ea803c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/bundler/bundler_2.3.14_linux_noarch_bionic_de0087f2.tgz"
    version = "2.3.14"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "a8930f903fea0db6cedb00c89a0c7c3ab876838858de6ab799e7c9df0204ff60"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["paketobuildpacks/build:full"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "e21d1e19d9e2ed30c589a294c5a2ff5b0ad603b01048c781c93db4543b1437b1"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu:22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "82187465a69301979ad42138801728ee0b93aa8a8a842371743909c33dffb4b0"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["paketobuildpacks/build:full"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "5afbad916b40fba4553dc8dbd00880906a50d14a0d2033539a52971be5db9208"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu:22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.16:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.16?checksum=4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672&download_url=https://rubygems.org/downloads/bundler-2.3.16.gem"
    sha256 = "d51c5135335218d879b6a37b4676452a9d095b1199443ca8899475e50bd7d426"
    source = "https://rubygems.org/downloads/bundler-2.3.16.gem"
    source_sha256 = "4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672"
    stacks = ["paketobuildpacks/build:full"]
    uri = "<UNKNOWN>"
    version = "2.3.16"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.16:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.16?checksum=4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672&download_url=https://rubygems.org/downloads/bundler-2.3.16.gem"
    sha256 = "f48d27d230363a670f9022241cbeb7d58f87861b8f6ca5d52461eb975c4ba957"
    source = "https://rubygems.org/downloads/bundler-2.3.16.gem"
    source_sha256 = "4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672"
    stacks = ["ubuntu:22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.16"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.16:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.16?checksum=4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672&download_url=https://rubygems.org/downloads/bundler-2.3.16.gem"
    sha256 = "7086f49dd3a0b2887e9d449f850f4c2cc9a1677c250f252e9c9f86eb2efcba38"
    source = "https://rubygems.org/downloads/bundler-2.3.16.gem"
    source_sha256 = "4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672"
    stacks = ["paketobuildpacks/build:full"]
    uri = "<UNKNOWN>"
    version = "2.3.16"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.16:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.16?checksum=4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672&download_url=https://rubygems.org/downloads/bundler-2.3.16.gem"
    sha256 = "6a4ec066f15db2bfa0ef54ad4ad4f35a864a06779d61f9b72d96aa2a880ff5d7"
    source = "https://rubygems.org/downloads/bundler-2.3.16.gem"
    source_sha256 = "4d6fbda60cdfa44f14a9918ca5d4e91b10509be22c0c724cdbcdeefaf186f672"
    stacks = ["ubuntu:22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.16"

  [[metadata.dependency-constraints]]
    constraint = "1.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 3

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
