api = "0.7"

[buildpack]
  description = "A buildpack for installing the approriate Bundler version"
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  keywords = ["ruby", "bundler"]
  name = "Paketo Bundler Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundler/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "6fb2e1a143c9131d4a5e74ada19fc47462d0fdff64ff47fdbe70d3762d940e68"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "e2ac106a3d05e82edb06607d210bbe8889479db180e4e5df148739a4af6feead"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "d9c306aca07d685fd4001e5bd49fae3b97e00d1b10008dbb13935951663bf1b4"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "7125cca43b26882dccfa900d242c80b4fae51fb6d39660ec068ce284002ba360"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "dde46f6200bee4cd56c029a2ce4584f9dba6c9b3447e0b226fa35189ad5fcf83"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.15:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.15?checksum=05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d&download_url=https://rubygems.org/downloads/bundler-2.3.15.gem"
    sha256 = "60e670487246d960177a1856f0350b95b14aa7374ecd15950e58cbb30f3c41db"
    source = "https://rubygems.org/downloads/bundler-2.3.15.gem"
    source_sha256 = "05b7a8a409982c5d336371dee433e905ff708596f332e5ef0379559b6968431d"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.14:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@2.3.14?checksum=2fae2925c22ae122b245416484373a139d57a3e123fe9baed98d407384ea803c&download_url=https://rubygems.org/downloads/bundler-2.3.14.gem"
    sha256 = "de0087f28b79870211e45e52776680e04c1d4c9c9f34fee0f48650e65f8f5c33"
    source = "https://rubygems.org/downloads/bundler-2.3.14.gem"
    source_sha256 = "2fae2925c22ae122b245416484373a139d57a3e123fe9baed98d407384ea803c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/bundler/bundler_2.3.14_linux_noarch_bionic_de0087f2.tgz"
    version = "2.3.14"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "5115977af4bd031047b33a7fe6f3060bd25281c5b425933c1dfb1209e2b0c150"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "f2f6be1a5a20f03943208a86b121af03051618ecff04ac293a7314c5c8e5d10a"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "c4fd091af5cc23e925b028deb300064688835ed07f8e47acba8b7941f7808d86"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-18.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "0eaf46bb1ab2285a40fb2a993983ee040869512a6cb4f91ac8a71c610b20f311"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "924ac4e5b399d873fd527cb107da14b6a2b0a8d653b220172244c0c21202fd7e"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["macos-latest"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:2.3.13:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/bundler@2.3.13?checksum=7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd&download_url=https://rubygems.org/downloads/bundler-2.3.13.gem"
    sha256 = "fd3136166f45126af2a851f347f813cdc4bfc464167674bc8b2a86ff650c748e"
    source = "https://rubygems.org/downloads/bundler-2.3.13.gem"
    source_sha256 = "7ec5e5caa8d21f7af9c106bd9091a96fa9f32104ecfc0b5f50ff25edf8a42dfd"
    stacks = ["ubuntu-22.04"]
    uri = "<UNKNOWN>"
    version = "2.3.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:bundler:bundler:1.17.3:*:*:*:*:ruby:*:*"
    id = "bundler"
    licenses = ["MIT", "MIT-0"]
    name = "Bundler"
    purl = "pkg:generic/bundler@1.17.3?checksum=bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352&download_url=https://rubygems.org/downloads/bundler-1.17.3.gem"
    sha256 = "dc89db5382e681b4c03b48dae8be4238b077a45e52488233ab01c0e93b913dc7"
    source = "https://rubygems.org/downloads/bundler-1.17.3.gem"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "file:///Users/caseyj/git/paketo-buildpacks/bundler/dependency/bundler-1.17.3.tgz"
    version = "1.17.3"

  [[metadata.dependency-constraints]]
    constraint = "1.*.*"
    id = "bundler"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "2.*.*"
    id = "bundler"
    patches = 3

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
