name: 'Build Bundler on Bionic'
description: |
  Build Bundler on Bionic

inputs:
  version:
    description: Version of dependency
    required: true
  tarball_name:
    description: output filename
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.tarball_name }}
    - "bionic"
