name: 'Build Bundler'
description: |
  Build Bundler

inputs:
  version:
    description: Version of dependency
    required: true
  tarball_name:
    description: output filename
    required: true
  target:
    description: GIMME THE DOCKERFILE
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile.${{ inputs.target }}'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.tarball_name }}
    - ${{ inputs.target }}
