name: 'Compile Dependency on Target'

description: |
  Compiles a dependency given a version, output directory, and a target image to compile on

inputs:
  version:
    description: 'dependency version'
    required: true
  outputDir:
    description: 'output directory'
    required: true
  target:
    description: 'dependency OS target variant'
    required: true

runs:
  using: 'docker'
  image: '${{ inputs.target }}.Dockerfile'
  args:
  - "--version"
  - ${{ inputs.version }}
  - "--outputDir"
  - ${{ inputs.outputDir }}
  - "--target"
  - ${{ inputs.target }}
