name: Dependency Compile Bundler

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the dependency
        required: true

jobs:
  compile:
    name: Compile Bundler
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Compile
        id: compile
        run: |
          pushd dependency > /dev/null
            make compile version="${VERSION}"
            echo "::set-output name=tarball_path::bundler-${VERSION}.tgz"
          popd > /dev/null
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Test
        run: |
          pushd dependency > /dev/null
            make test version="${VERSION}" tarball_path="${{ steps.compile.outputs.tarball_path }}"
          popd > /dev/null
        env:
          VERSION: ${{ github.event.inputs.version }}

