name: Dependencies

on:
  workflow_dispatch:
#    inputs:
#      version:
#        description: Version of the dependency
#        required: true

jobs:
  compile:
    name: Compile Bundler
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-22.04
        - macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Retrieve new version
        id: retrieve
        run: |
          pushd dependency > /dev/null
            echo "::set-output name=new_version::$(make retrieve)"
          popd > /dev/null
      - name: Compile
        id: compile
        run: |
          pushd dependency > /dev/null
            make compile version="${VERSION}"
            echo "::set-output name=tarball_path::bundler-${VERSION}.tgz"
          popd > /dev/null
        env:
          VERSION: ${{ steps.retrieve.outputs.new_version }}
      - name: Test
        run: |
          pushd dependency > /dev/null
            make test version="${VERSION}" tarball_path="${{ steps.compile.outputs.tarball_path }}"
          popd > /dev/null
        env:
          VERSION: ${{ github.event.inputs.version }}

