name: Dependencies Compile

on:
  workflow_dispatch:
#    inputs:
#      version:
#        description: Version of the dependency
#        required: true

jobs:
  compile:
    name: Compile Bundler
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-22.04
        - macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup go >=1.18.0
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Retrieve new version
        id: retrieve
        run: |
          pushd dependency > /dev/null
            versions=$(make retrieve)
            echo "Found versions ${versions}"
            echo "::set-output name=new_version::${versions}"
          popd > /dev/null
      - name: Compile ${{ steps.retrieve.outputs.new_version }}
        id: compile
        run: |
          pushd dependency > /dev/null
            make compile version="${VERSION}"
            echo "::set-output name=tarball_path::bundler-${VERSION}.tgz"
          popd > /dev/null
        env:
          VERSION: ${{ steps.retrieve.outputs.new_version }}
      - name: Test ${{ steps.retrieve.outputs.new_version }}
        run: |
          pushd dependency > /dev/null
            make test version="${VERSION}" tarball_path="${{ steps.compile.outputs.tarball_path }}"
          popd > /dev/null
        env:
          VERSION: ${{ steps.retrieve.outputs.new_version }}
