name: Dependencies (Retrieve, Metadata, Compile, Test, Create PR)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # https://crontab.guru/every-12-hours
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  select-go-version:
    name: Select Go Version
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.select-go-version.outputs.go-version }}
    steps:
      - name: Select Go Version
        id: select-go-version
        run: echo "::set-output name=go-version::>=1.18.0"
  # TODO: what happens when there are no new versions
  retrieve:
    name: Retrieve new versions and generate metadata
    needs:
      - select-go-version
    runs-on: ubuntu-latest
    outputs:
      metadata-filepath: ${{ steps.retrieve.outputs.metadata-filepath }}
      metadata-json: ${{ steps.retrieve.outputs.metadata-json }}
      id: ${{ steps.retrieve.outputs.id }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup go '${{ needs.select-go-version.outputs.go-version }}'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.select-go-version.outputs.go-version }}
      - name: Run Retrieve
        id: retrieve
        working-directory: dependency
        run: |
          OUTPUT="/tmp/metadata.json"

          make retrieve \
            buildpackTomlPath="${{ github.workspace }}/buildpack.toml" \
            output="${OUTPUT}"

          id=`cat "${OUTPUT}" | jq -r .[0].id`
          content=`cat "${OUTPUT}" | jq -r`

          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"

          echo "::set-output name=metadata-filepath::${OUTPUT}"
          echo "::set-output name=metadata-json::$content"
          echo "::set-output name=id::$id"
      ## TODO do we need this?
      - name: Upload `${{ steps.retrieve.outputs.metadata-filepath }}`
        uses: actions/upload-artifact@v3
        with:
          name: metadata.json
          path: ${{ steps.retrieve.outputs.metadata-filepath }}
  get-action:
    name: Get Compilation Action
    outputs:
      should-compile: ${{ steps.compile-check.outputs.should-compile }}
      should-test: ${{ steps.test-check.outputs.should-test }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Has Compilation Action?
        id: compile-check
        run: |
          if test -d "dependency/actions/compile"; then
            echo "Compilation action provided"
            echo "::set-output name=should-compile::true"
          fi
      - name: Has Testing Action?
        id: test-check
        run: |
          if test -d "dependency/test"; then
            echo "Testing file provided"
            echo "::set-output name=should-test::true"
          fi
  compile:
    name: Compile and Test
    needs:
      - retrieve
      - get-action
    strategy:
      matrix:
        includes: ${{ fromJSON(needs.retrieve.outputs.metadata-json) }}
    if: ${{ needs.get-action.outputs.should-compile == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Make Temporary Artifact Directory
        id: make-outputdir
        run: |
          echo "::set-output name=outputdir::$(mktemp -d)"
      - name: Parse matrix
        id: parse-matrix
        run: |
          echo '${{ matrix.includes.version }}'
          echo '${{ matrix.includes.target }}'
      - name: Compile version ${{ matrix.includes.version }} on ${{ matrix.includes.target }} Dockerfile
        id: compile
        if: ${{ matrix.includes.sha256 == '' && matrix.includes.uri == '' }}
        uses: ./dependency/actions/compile
        with:
          version: "${{ matrix.includes.version }}"
          outputDir: "${{ steps.make-outputdir.outputs.outputdir }}"
          target: "${{ matrix.includes.target }}"
      - name: Upload
        uses: actions/upload-artifact@v3
        if: ${{ matrix.includes.sha256 == '' && matrix.includes.uri == '' }}
        with:
          name: '${{ needs.retrieve.outputs.id }}-${{ matrix.includes.version }}-${{ matrix.includes.target }}'
          path: '${{ steps.make-outputdir.outputs.outputdir }}/*'
      ## TODO:
      #   add a bucket upload mechanism
      #   add a step for when upload happens, we update the SHA and URI (steps.parse-matrix.outputs.uri updated)
      #   tje Update SHA256 and URi step will change.
      - name: Update SHA256 and URI
        if: ${{ matrix.includes.sha256 == '' && matrix.includes.uri == '' }}
        run: |
          newPath="${{ steps.make-outputdir.outputs.outputdir }}/.tgz"
          ${{ steps.parse-matrix.outputs.uri  }} = newPath
      - name: Test
        working-directory: dependency
        if: ${{ needs.get-action.outputs.should-test == 'true' }}
         #TODO: if there is a test
        run: |
          make test \
            version="${{ matrix.includes.version }}" \
            tarballPath="${{ steps.make-outputdir.outputs.outputdir }}/.tgz"

  # assemble:
  #   name: Assemble Metadata information
  #   needs:
  #     - metadata
  #     - compile
  #     - select-go-version
  #     - retrieve
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: Setup go '${{ needs.select-go-version.outputs.go-version }}'
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ needs.select-go-version.outputs.go-version }}
  #     - name: Setup temp dir
  #       id: setup-temp-dir
  #       run: |
  #         echo "::set-output name=artifactPath::$(mktemp -d)"
  #     - name: Get all artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: ${{ steps.setup-temp-dir.outputs.artifactPath }}
  #     - name: List everything
  #       working-directory: ${{ steps.setup-temp-dir.outputs.artifactPath }}
  #       run: ls -lsaRth
  #     - name: Run assemble
  #       working-directory: libdependency
  #       run: |
  #         make assemble \
  #           id="${{ needs.retrieve.outputs.id }}" \
  #           artifactPath=${{ steps.setup-temp-dir.outputs.artifactPath }} \
  #           buildpackTomlPath=${{ github.workspace }}/buildpack.toml
  #     - name: Checkout Branch 'automation/dependencies/update'
  #       uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
  #       with:
  #         branch: automation/dependencies/update
  #     - name: Show git diff
  #       run: |
  #         cat ${{ github.workspace }}/buildpack.toml
  #         git diff
  #     - name: Commit
  #       id: commit
  #       uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
  #       with:
  #         message: "Updating buildpack.toml with new versions ${{ needs.retrieve.outputs.new_versions }}"
  #         pathspec: "."
  #     - name: Push Branch 'automation/dependencies/update'
  #       if: ${{ steps.commit.outputs.commit_sha != '' }}
  #       uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
  #       with:
  #         branch: automation/dependencies/update
  # submit-pull-request:
  #   name: Submit Pull Request
  #   needs:
  #     - assemble
  #     - retrieve
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #       with:
  #         ref: automation/dependencies/update
  #     - name: Open Pull Request
  #       run: |
  #         gh pr create \
  #           --title "Updates buildpack.toml with ${{ needs.retrieve.outputs.new_versions }}" \
  #           --body "See commit history for details" \
  #           --base main
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
