name: Dependencies (Retrieve, Metadata, Compile, Test, Create PR)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # https://crontab.guru/every-12-hours

jobs:
  get_operating_systems:
    name: Get Operating Systems
    runs-on: ubuntu-latest
    outputs:
      operating_systems: ${{ steps.get_operating_systems.outputs.operating_systems }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get Operating Systems
        id: get_operating_systems
        run: |
          operatingSystems=$(cat dependency/operating_systems.json)
          echo "Found operatingSystems ${operatingSystems}"
          echo "::set-output name=operating_systems::${operatingSystems}"
      - name: Found ${{ steps.get_operating_systems.outputs.operating_systems }}
        run: echo ${{ steps.get_operating_systems.outputs.operating_systems }}
  retrieve:
    name: Retrieve new versions
    runs-on: ubuntu-latest
    outputs:
      new_versions: ${{ steps.retrieve.outputs.new_versions }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup go >=1.18.0
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Retrieve new versions
        id: retrieve
        run: |
          pushd dependency > /dev/null
            versions=$(make retrieve)
            echo "Found versions ${versions}"
            echo "::set-output name=new_versions::${versions}"
          popd > /dev/null
      - name: Found ${{ steps.retrieve.outputs.new_versions }}
        run: echo ${{ steps.retrieve.outputs.new_versions }}
  metadata:
    name: Retrieve metadata for new versions
    needs:
      - retrieve
    strategy:
      matrix:
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{ steps.metadata.outputs.metadata }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Add Metadata for version
        id: metadata
        run: |
          set -euo pipefail
          pushd dependency > /dev/null
            metadata=$(make metadata version="${{ matrix.version }}")
            echo "${metadata}" > "metadata-${{ matrix.version }}.json"
            echo "::set-output name=metadata::${metadata}"
          popd > /dev/null
      - name: Found ${{ steps.metadata.outputs.metadata }}
        run: echo ${{ steps.metadata.outputs.metadata }}
      - name: Cache Metadata for ${{ matrix.version }}
        uses: actions/cache@v3
        with:
          path: dependency/metadata-${{ matrix.version }}.json
          key: metadata-${{ matrix.version }}.json
  compile:
    name: Compile Bundler
    needs:
      - get_operating_systems
      - retrieve
    strategy:
      matrix:
        os: ${{ fromJSON(needs.get_operating_systems.outputs.operating_systems) }}
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          pushd dependency > /dev/null
            make prepare os="${{ matrix.os }}"
          popd > /dev/null
      - name: Compile ${{ matrix.version }}
        id: compile
        run: |
          pushd dependency > /dev/null
            tarball_name="bundler-${{ matrix.version }}-${{ matrix.os }}.tgz"
            make compile version="${{ matrix.version }}" tarball_name="${tarball_name}"
            echo "::set-output name=tarball_name::${tarball_name}"
          popd > /dev/null
      - name: Test 'bundler-${{ matrix.version }}-${{ matrix.os }}.tgz'
        run: |
          pushd dependency > /dev/null
            make test version="${{ matrix.version }}" tarball_name="${{ steps.compile.outputs.tarball_name }}" os="${{ matrix.os }}"
          popd > /dev/null
      - name: Cache Tarball for ${{ matrix.version }}
        uses: actions/cache@v3
        with:
          path: dependency/${{ steps.compile.outputs.tarball_name }}
          key: dependency/${{ steps.compile.outputs.tarball_name }}
  create-pull-request:
    name: Create Pull Request
    needs:
      - retrieve
      - metadata
      - compile
    strategy:
      matrix:
        os: ${{ fromJSON(needs.get_operating_systems.outputs.operating_systems) }}
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Retrieve Metadata for ${{ matrix.version }}
        uses: actions/cache@v3
        with:
          path: dependency/metadata-${{ matrix.version }}.json
          key: metadata-${{ matrix.version }}.json
      - name: Print dependency/metadata-${{ matrix.version }}.json
        run: cat dependency/metadata-${{ matrix.version }}.json
      - name: Retrieve Tarball for ${{ matrix.version }}-${{ matrix.os }}
        uses: actions/cache@v3
        with:
          path: dependency/bundler-${{ matrix.version }}-${{ matrix.os }}.tgz
          key: dependency/bundler-${{ matrix.version }}-${{ matrix.os }}.tgz
      - name: Describe dependency/bundler-${{ matrix.version }}-${{ matrix.os }}.tgz
        run: |
          ls -lsa dependency/bundler-${{ matrix.version }}-${{ matrix.os }}.tgz
          gensha256 dependency/bundler-${{ matrix.version }}-${{ matrix.os }}.tgz
