name: Dependencies (Retrieve, Metadata, Compile, Test, Create PR)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # https://crontab.guru/every-12-hours

jobs:
  get_operating_systems:
    name: Get Operating Systems
    runs-on: ubuntu-latest
    outputs:
      operating_systems: ${{ steps.get_operating_systems.outputs.operating_systems }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get Operating Systems
        id: get_operating_systems
        run: |
          operatingSystems=$(cat dependency/operating_systems.json)
          echo "Found operatingSystems ${operatingSystems}"
          echo "::set-output name=operating_systems::${operatingSystems}"
      - name: Found ${{ steps.get_operating_systems.outputs.operating_systems }}
        run: echo ${{ steps.get_operating_systems.outputs.operating_systems }}
  retrieve:
    name: Retrieve new versions
    runs-on: ubuntu-latest
    outputs:
      new_versions: ${{ steps.retrieve.outputs.new_versions }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup go >=1.18.0
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Retrieve new versions
        id: retrieve
        run: |
          pushd dependency > /dev/null
            versions=$(make retrieve)
            echo "Found versions ${versions}"
            echo "::set-output name=new_versions::${versions}"
          popd > /dev/null
      - name: Found ${{ steps.retrieve.outputs.new_versions }}
        run: echo ${{ steps.retrieve.outputs.new_versions }}
  metadata:
    name: Retrieve metadata for new versions
    needs:
      - retrieve
    strategy:
      matrix:
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{ steps.metadata.outputs.metadata }}
      uri: ${{ steps.metadata.outputs.uri }}
      sha256: ${{ steps.metadata.outputs.sha256 }}
      release-date: ${{ steps.metadata.outputs.release-date }}
      deprecation-date: ${{ steps.metadata.outputs.deprecation-date }}
      cpe: ${{ steps.metadata.outputs.cpe }}
      purl: ${{ steps.metadata.outputs.purl }}
      licenses: ${{ steps.metadata.outputs.licenses }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Add Metadata for version
        id: metadata
        run: |
          set -euo pipefail
          pushd dependency > /dev/null
            metadata=$(make metadata version="${{ matrix.version }}")
          
            echo "::set-output name=metadata::${metadata}"
            echo "::set-output name=uri::$(jq -r .uri <<< "${metadata}")"
            echo "::set-output name=sha256::$(jq -r .sha256 <<< "${metadata}")"
            echo "::set-output name=release-date::$(jq -r '.release_date // empty' <<< "${metadata}")"
            echo "::set-output name=deprecation-date::$(jq -r '.deprecation_date // empty' <<< "${metadata}")"
            echo "::set-output name=cpe::$(jq -r .cpe <<< "${metadata}")"
            echo "::set-output name=purl::$(jq -r .purl <<< "${metadata}")"
            echo "::set-output name=licenses::$(jq -c .licenses <<< "${metadata}")"
          popd > /dev/null
      - name: Found ${{ steps.metadata.outputs.metadata }}
        run: echo ${{ steps.metadata.outputs.metadata }}
  compile:
    name: Compile Bundler
    needs:
      - get_operating_systems
      - retrieve
    strategy:
      matrix:
        os: ${{ fromJSON(needs.get_operating_systems.outputs.operating_systems) }}
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          pushd dependency > /dev/null
            make prepare os="${{ matrix.os }}"
          popd > /dev/null
      - name: Compile ${{ matrix.version }}
        id: compile
        run: |
          pushd dependency > /dev/null
            make compile version="${{ matrix.version }}"
            echo "::set-output name=tarball_path::bundler-${{ matrix.version }}.tgz"
          popd > /dev/null
      - name: Test ${{ matrix.version }}
        run: |
          pushd dependency > /dev/null
            make test version="${{ matrix.version }}" tarball_path="${{ steps.compile.outputs.tarball_path }}" os="${{ matrix.os }}"
          popd > /dev/null
