name: Dependencies (Retrieve, Metadata, Compile, Test, Create PR)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # https://crontab.guru/every-12-hours
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  select-go-version:
    name: Select Go Version
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.select-go-version.outputs.go-version }}
    steps:
      - name: Select Go Version
        id: select-go-version
        run: echo "::set-output name=go-version::>=1.18.0"
  get_branch_name:
    name: Get Branch Name
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.setup-branch-name.outputs.branch-name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup branch name
        id: setup-branch-name
        run: echo "::set-output name=branch-name::automation/dependencies/bump-$(git rev-parse --short HEAD)-$(date +%s)"
  get_operating_systems:
    name: Get Operating Systems
    runs-on: ubuntu-latest
    outputs:
      operating_systems: ${{ steps.get_operating_systems.outputs.operating_systems }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get Operating Systems
        id: get_operating_systems
        run: |
          operatingSystems=$(cat dependency/operating_systems.json)
          echo "Found operatingSystems ${operatingSystems}"
          echo "::set-output name=operating_systems::${operatingSystems}"
      - name: Found '${{ steps.get_operating_systems.outputs.operating_systems }}'
        run: echo ${{ steps.get_operating_systems.outputs.operating_systems }}
  retrieve:
    name: Retrieve new versions
    needs:
      - select-go-version
    runs-on: ubuntu-latest
    outputs:
      new_versions: ${{ steps.retrieve.outputs.new_versions }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup go '${{ needs.select-go-version.outputs.go-version }}'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.select-go-version.outputs.go-version }}
      - name: Retrieve new versions
        id: retrieve
        working-directory: dependency
        run: |
          versions=$(make retrieve)
          echo "Found versions ${versions}"
          echo "::set-output name=new_versions::${versions}"
      - name: Found '${{ steps.retrieve.outputs.new_versions }}'
        run: echo ${{ steps.retrieve.outputs.new_versions }}
  metadata:
    name: Retrieve metadata for new versions
    needs:
      - retrieve
    strategy:
      matrix:
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{ steps.metadata.outputs.metadata }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get metadata filepath
        id: get-metadata-filepath
        run: |
          echo "::set-output name=metadata-filepath::${{ github.workspace }}/metadata-${{ matrix.version }}.json"
      - name: Add Metadata for version
        id: metadata
        working-directory: dependency
        run: |
          make metadata \
            version="${{ matrix.version }}" \
            output="${{ steps.get-metadata-filepath.outputs.metadata-filepath }}"
      - name: Output metadata '${{ steps.get-metadata-filepath.outputs.metadata-filepath }}'
        working-directory: dependency
        run: cat ${{ steps.get-metadata-filepath.outputs.metadata-filepath }}
      - name: Upload `${{ steps.get-metadata-filepath.outputs.metadata-filepath }}'
        uses: actions/upload-artifact@v3
        with:
          name: metadata-${{ matrix.version }}.json
          path: ${{ steps.get-metadata-filepath.outputs.metadata-filepath }}
  compile:
    name: Compile
    needs:
      - get_operating_systems
      - retrieve
    strategy:
      matrix:
        os: ${{ fromJSON(needs.get_operating_systems.outputs.operating_systems) }}
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup tarball name
        id: tarball_name
        run: |
          echo "::set-output name=tarball_name::$(cat dependency/ID)-${{ matrix.version }}-${{ matrix.os }}"
      - name: Prepare '${{ matrix.os }}'
        run: . dependency/prepare/${{ matrix.os }}
      - name: Compile '${{ steps.tarball_name.outputs.tarball_name }}'
        id: compile
        working-directory: dependency
        run: |
          make compile \
            version="${{ matrix.version }}" \
            tarball_name="${{ steps.tarball_name.outputs.tarball_name }}.tgz" \
            os="${{ matrix.os }}"
      - name: Test '${{ steps.tarball_name.outputs.tarball_name }}'
        working-directory: dependency
        run: |
          make test \
            version="${{ matrix.version }}" \
            tarball_name="${{ steps.tarball_name.outputs.tarball_name }}.tgz"
      - name: Upload '${{ steps.tarball_name.outputs.tarball_name }}'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.tarball_name.outputs.tarball_name }}
          path: 'dependency/${{ steps.tarball_name.outputs.tarball_name }}.tgz*'
  prepare-commits:
    name: Prepare Commits
    needs:
      - get_branch_name
      - get_operating_systems
      - retrieve
      - metadata
      - compile
    strategy:
      max-parallel: 1 # Very important! Commits will clobber each other
      matrix:
        os: ${{ fromJSON(needs.get_operating_systems.outputs.operating_systems) }}
        version: ${{ fromJSON(needs.retrieve.outputs.new_versions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Checkout Branch '${{ needs.get_branch_name.outputs.branch-name }}'
        uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
        with:
          branch: ${{ needs.get_branch_name.outputs.branch-name }}
      - name: Setup tarball name
        id: tarball_name
        run: |
          echo "::set-output name=tarball_name::$(cat dependency/ID)-${{ matrix.version }}-${{ matrix.os }}.tgz"
      - name: Download 'metadata-${{ matrix.version }}.json'
        uses: actions/download-artifact@v3
        with:
          name: metadata-${{ matrix.version }}.json
          path: dependency/
      - name: Print 'dependency/metadata-${{ matrix.version }}.json'
        run: cat dependency/metadata-${{ matrix.version }}.json
      - name: Download '${{ steps.tarball_name.outputs.tarball_name }}'
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.tarball_name.outputs.tarball_name }}
          path: dependency/
      - name: Describe 'dependency/${{ steps.tarball_name.outputs.tarball_name }}'
        run: |
          ls -lsa dependency/${{ steps.tarball_name.outputs.tarball_name }}
      - name: Prepare Commit
        working-directory: libdependency
        run: |
          make prepare-commit \
            metadataPath="${PWD}/metadata-${{ matrix.version }}.json" \
            tarballName="${PWD}/${{ steps.tarball_name.outputs.tarball_name }}" \
            id="$(cat ${{ github.workspace }}/dependency/ID)" \
            version="${{ matrix.version }}" \
            os="${{ matrix.os }}"
      - name: Cleanup 'metadata-${{ matrix.version }}.json'
        run: |
          rm dependency/metadata-${{ matrix.version }}.json
      - name: Cleanup '${{ steps.tarball_name.outputs.tarball_name }}'
        run: |
          rm dependency/${{ steps.tarball_name.outputs.tarball_name }}
      - name: Show git diff
        run: git diff
      - name: Commit
        id: commit
        uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
        with:
          message: "Updating dependencies in buildpack.toml with ${{ matrix.version }}-${{ matrix.os }}"
          pathspec: "."
      - name: Push Branch '${{ needs.get_branch_name.outputs.branch-name }}'
        uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
        with:
          branch: ${{ needs.get_branch_name.outputs.branch-name }}
  prune:
    name: Prune old versions
    needs:
      - get_branch_name
      - prepare-commits
    runs-on: ubuntu-latest
    steps:
      - name: Setup go '${{ needs.select-go-version.outputs.go-version }}'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.select-go-version.outputs.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.get_branch_name.outputs.branch-name }}
      - name: Prune
        working-directory: libdependency
        run: |
          make prune
      - name: Commit
        id: commit
        uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
        with:
          message: "Pruning buildpack.toml"
          pathspec: "."
      - name: Push Branch '${{ needs.get_branch_name.outputs.branch-name }}'
        uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
        with:
          branch: ${{ needs.get_branch_name.outputs.branch-name }}
  submit-pull-request:
    name: Submit Pull Request
    needs:
      - get_branch_name
      - retrieve
      - prepare-commits
      - prune
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.get_branch_name.outputs.branch-name }}
      - name: PR Title
        id: title
        run: |
          echo "::set-output name=include_versions:: with new dependency versions: ${{ matrix.version }}"
      - name: Open Pull Request
        run: |
          gh pr create \
            --title "Updates buildpack.toml with ${{ needs.retrieve.outputs.new_versions }}" \
            --body "See commit history for details" \
            --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  assemble:
    name: Assemble Metadata information
    needs:
      - metadata
      - compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.get_branch_name.outputs.branch-name }}
      - name: Setup temp dir
        id: setup-temp-dir
        run: |
          echo "::set-output name=artifactPath::$(mktemp -d)"
      - name: Get all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ steps.setup-temp-dir.outputs.artifactPath }}
      - name: List everything
        working-directory: ${{ steps.setup-temp-dir.outputs.artifactPath }}
        run: ls -lsaRth
      - name: Run assemble
        working-directory: libdependency
        run: |
          make assemble \
            id="$(cat ${{ github.workspace }}/dependency/ID)" \
            artifactPath=${{ steps.setup-temp-dir.outputs.artifactPath }} \
            buildpackTomlPath=${{ github.workspace }}/buildpack.toml
