name: Dependencies (Retrieve, Metadata, Compile, Test, Create PR)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # https://crontab.guru/every-12-hours
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  select-go-version:
    name: Select Go Version
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.select-go-version.outputs.go-version }}
    steps:
      - name: Select Go Version
        id: select-go-version
        run: echo "::set-output name=go-version::>=1.18.0"
  # TODO: what happens when there are no new versions
  retrieve:
    name: Retrieve New Versions and Generate Metadata
    needs:
      - select-go-version
    runs-on: ubuntu-latest
    outputs:
      metadata-filepath: ${{ steps.retrieve.outputs.metadata-filepath }}
      metadata-json: ${{ steps.retrieve.outputs.metadata-json }}
      id: ${{ steps.retrieve.outputs.id }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup go '${{ needs.select-go-version.outputs.go-version }}'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.select-go-version.outputs.go-version }}
      - name: Run Retrieve
        id: retrieve
        working-directory: dependency
        run: |
          OUTPUT="/tmp/metadata.json"

          make retrieve \
            buildpackTomlPath="${{ github.workspace }}/buildpack.toml" \
            output="${OUTPUT}"

          id=`cat "${OUTPUT}" | jq -r .[0].id`
          content=`cat "${OUTPUT}" | jq -r`

          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"

          echo "::set-output name=metadata-filepath::${OUTPUT}"
          echo "::set-output name=metadata-json::$content"
          echo "::set-output name=id::$id"
      ## TODO do we need this?
      - name: Upload `${{ steps.retrieve.outputs.metadata-filepath }}`
        uses: actions/upload-artifact@v3
        with:
          name: metadata.json
          path: ${{ steps.retrieve.outputs.metadata-filepath }}
  get-action:
    name: Get Compilation and Testing Code
    outputs:
      should-compile: ${{ steps.compile-check.outputs.should-compile }}
      should-test: ${{ steps.test-check.outputs.should-test }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Has Compilation Action?
        id: compile-check
        run: |
          if test -d "dependency/actions/compile"; then
            echo "Compilation action provided"
            echo "::set-output name=should-compile::true"
          fi
      - name: Has Testing Action?
        id: test-check
        run: |
          if test -d "dependency/test"; then
            echo "Testing file provided"
            echo "::set-output name=should-test::true"
          fi
  # Compilation will be skipped if no compilation action is provided
  # Compilation for a specific version/target will be skipped if the SHA256/URI
  # fields in its metadata are already filled out.
  compile:
    name: Compile and Test
    needs:
      - retrieve
      - get-action
    strategy:
      matrix:
        includes: ${{ fromJSON(needs.retrieve.outputs.metadata-json) }}
    if: ${{ needs.get-action.outputs.should-compile == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Make Temporary Artifact Directory
        id: make-outputdir
        run: |
          echo "::set-output name=outputdir::$(mktemp -d)"
      - name: Parse matrix
        id: parse-matrix
        run: |
          echo '${{ matrix.includes.version }}'
          echo '${{ matrix.includes.target }}'
      - name: Compile version ${{ matrix.includes.version }} on ${{ matrix.includes.target }} Dockerfile
        id: compile
        if: ${{ matrix.includes.sha256 == '' && matrix.includes.uri == '' }}
        uses: ./dependency/actions/compile
        with:
          version: "${{ matrix.includes.version }}"
          outputdir: "${{ steps.make-outputdir.outputs.outputdir }}"
          target: "${{ matrix.includes.target }}"
      - name: Upload workflow asset
        uses: actions/upload-artifact@v3
        if: ${{ matrix.includes.sha256 == '' && matrix.includes.uri == '' }}
        with:
          name: '${{ needs.retrieve.outputs.id }}-${{ matrix.includes.version }}-${{ matrix.includes.target }}'
          path: '${{ steps.make-outputdir.outputs.outputdir }}/*'
      # TODO: separate testing?
      - name: Test Dependency
        working-directory: dependency
        if: ${{ needs.get-action.outputs.should-test == 'true' }}
        run: |
          make test \
            version="${{ matrix.includes.version }}" \
            tarballPath="${{ steps.make-outputdir.outputs.outputdir }}/*.tgz"
  update-metadata:
    name: Update Metadata (if compiled)
    needs:
      - retrieve
      - get-action
      - compile
    strategy:
      matrix:
        includes: ${{ fromJSON(needs.retrieve.outputs.metadata-json) }}
      # Run metadata update step in parallel so that metadata.json can be
      # modified for each version
      max-parallel: 1
    if: ${{ needs.get-action.outputs.should-compile == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      ## TODO:
      #   add a bucket upload mechanism
      #   add a step for when upload happens, we update the SHA and URI (steps.parse-matrix.outputs.uri updated)
      #   tje Update SHA256 and URi step will change.
      - name: Download metadata.json
        uses: actions/download-artifact@v3
        with:
          name: metadata.json
      - name: Update `sha256` and `uri` in metadata for ${{ matrix.includes.target }} ${{ matrix.includes.version }}
        if: ${{ matrix.includes.sha256 == '' && matrix.includes.uri == '' }}
        uses: ./dependency/actions/update-json
        with:
          version: "${{ matrix.includes.version }}"
          target: "${{ matrix.includes.target }}"
          sha256: "123456"
          uri: "123456"
          file: "metadata.json"
      - name: Upload modified metadata
        uses: actions/upload-artifact@v3
        with:
          name: metadata.json
          path: metadata.json

  assemble:
    name: Update buildpack.toml
    needs:
      - retrieve
      - compile
      - update-metadata
    if: ${{ always() && needs.retrieve.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Checkout Branch
        uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
        with:
          branch: automation/dependencies/update-from-metadata

      - name: Make Temporary Artifact Directory
        id: make-outputdir
        run: |
          echo "::set-output name=outputdir::$(mktemp -d)"

      - name: Download metadata.json
        uses: actions/download-artifact@v3
        with:
          name: metadata.json
          path: "${{ steps.make-outputdir.outputs.outputdir }}"

      - name: Update dependencies from metadata.json
        id: update
        # TODO change this path
        uses: ./dependency/actions/update
        with:
          buildpack_toml_path: "${{ github.workspace }}/buildpack.toml"
          metadata_file_path: "${{ steps.make-outputdir.outputs.outputdir }}/metadata.json"
      - name: Show git diff
        run: |
          git diff
      - name: Commit
        id: commit
        uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
        with:
          message: "Updating buildpack.toml with new versions ${{ steps.update.outputs.new-versions }}"
          pathspec: "."

      - name: Push Branch 'automation/dependencies/update-from-metadata'
        if: ${{ steps.commit.outputs.commit_sha != '' }}
        uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
        with:
          branch: automation/dependencies/update-from-metadata

      - name: Open Pull Request
        if: ${{ steps.commit.outputs.commit_sha != '' }}
        uses: paketo-buildpacks/github-config/actions/pull-request/open@main
        with:
          #TODO: CHANGE THIS TOKEN and any others
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Updates buildpack.toml with ${{ steps.update.outputs.new-versions }}"
          branch: automation/buildpack.toml/update-from-metadata
