name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  matrix-actions:
    name: Run matrix actions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - jammy
          - bionic
          - alpine
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Compile
        uses: joshuatcasey/bundler/dependency/actions/compile@main
        with:
          version: 2.3.13
          tarball_name: bundler-2.3.13.tgz
          target: ${{ matrix.image }}